/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_gestion (void);
GtkWidget* create_fenetre_ajout_bv (void);
GtkWidget* create_fenetre_liste_bv (void);
GtkWidget* create_fenetre_modfi_bv (void);
GtkWidget* create_erreur_bv (void);
