/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *fenetre_gestion;
  GtkWidget *fenetre_ajout_bv;
  GtkWidget *fenetre_liste_bv;
  GtkWidget *fenetre_modfi_bv;
  GtkWidget *erreur_bv;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  fenetre_gestion = create_fenetre_gestion ();
  gtk_widget_show (fenetre_gestion);
  /*
  fenetre_ajout_bv = create_fenetre_ajout_bv ();
  gtk_widget_show (fenetre_ajout_bv);
  fenetre_liste_bv = create_fenetre_liste_bv ();
  gtk_widget_show (fenetre_liste_bv);
  fenetre_modfi_bv = create_fenetre_modfi_bv ();
  gtk_widget_show (fenetre_modfi_bv);
  erreur_bv = create_erreur_bv ();
  gtk_widget_show (erreur_bv);
  */

  gtk_main ();
  return 0;
}

